version: "2.0"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5431:5432"
  postgres_audit:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5430:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2183"
  kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "audit_topic:1:3"
      depends_on:
        - zookeeper
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - /home/barry/mongodb/database:/data/db
    ports:
        - 27011:27017
    restart: unless-stopped
