spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
        ddl-auto: none
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5431/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  liquibase:
    change-log: classpath:db/changelog/init.xml
  boot:
    admin:
      client:
        url: ${ADMIN_CLIENT_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/client.log
    path: logs